(function () {
  'use strict';

  // The buyer intake form. Reads js/intake-catalog.json (generated by
  // scripts/gen-intake-catalog.mjs: sections, tiers and plain-English copy, no
  // prices), walks the buyer through ten short pages, and saves after every
  // page through /api/intake so they can leave and come back on any device.
  //
  // Sign-in is the same Supabase pattern as pricing.html (email code, Google,
  // LinkedIn). Nothing here computes or shows a price; the answers are tier
  // keys, counts and free text, and the estimate is made by a person.

  var ENV = window.EDH_INTAKE_ENV || {
    local: false,
    supabaseUrl: 'https://thqrhletflxbrarymxkk.supabase.co',
    supabaseKey: 'sb_publishable_qmyFRgCY-GvUowD9qBWvRg_McxEPdbJ'
  };
  var SB = supabase.createClient(ENV.supabaseUrl, ENV.supabaseKey);
  window.SB = SB;

  var M2_TO_FT2 = 10.7639;
  var TIERS = ['good', 'better', 'best'];
  var TIER_LABEL = { good: 'Good', better: 'Better', best: 'Best' };

  var COUNTRIES = ['United States', 'Portugal', 'Canada', 'United Kingdom', 'Ireland', 'Spain', 'France', 'Germany',
    'Netherlands', 'Belgium', 'Italy', 'Switzerland', 'Austria', 'Australia', 'New Zealand', 'Mexico', 'Brazil', 'Other'];

  // ---- state -------------------------------------------------------------------
  var catalog = null;
  var state = {
    session: null,
    step: 0,
    answers: emptyAnswers(),
    saveTimer: null,
    saving: false,
    lastSaved: null,
    resumed: false
  };

  function emptyAnswers() {
    return {
      contact: { name: '', phone: '' },
      site: { country: '', region: '', address: '', ownership: '', access: '', utilities: [], notes: '' },
      building: { domes: 1, diameters: '', floors: '', foundation: '', area_m2: null, area_ft2: null, area_entered: 'm2' },
      program: { bedrooms: null, bathrooms: null, half_baths: 0, garage: '', office: '', other_rooms: '' },
      sections: {},
      systems: { electricity: '', notes: '' },
      timeline: { start: '', budget: '', currency: '', notes: '' }
    };
  }

  // Merge a saved draft over the empty shape so a field added after the draft
  // was written still exists.
  function mergeAnswers(saved) {
    var base = emptyAnswers();
    if (!saved || typeof saved !== 'object') return base;
    Object.keys(base).forEach(function (k) {
      if (saved[k] && typeof saved[k] === 'object') {
        Object.keys(saved[k]).forEach(function (f) { base[k][f] = saved[k][f]; });
      }
    });
    return base;
  }

  // ---- steps -------------------------------------------------------------------
  var STEPS = [
    { key: 'site', pill: 'Site', title: 'Where will the house stand?', intro: 'What we know about the land shapes everything after it. If you are still searching, tell us where you are looking.' },
    { key: 'building', pill: 'Building', title: 'The building', intro: 'Rough numbers are fine. We refine all of this together once we have a site plan.' },
    { key: 'program', pill: 'Rooms', title: 'The rooms', intro: 'What the house needs to hold.' },
    { key: 'kitchen_bath', pill: 'Kitchen and baths', group: 'kitchen_bath' },
    { key: 'interior', pill: 'Interior', group: 'interior' },
    { key: 'exterior', pill: 'Exterior', group: 'exterior' },
    { key: 'water_outdoors', pill: 'Water and outdoors', group: 'water_outdoors' },
    { key: 'systems', pill: 'Systems', title: 'Heating, cooling, water and power', intro: 'How the house stays comfortable and where its energy comes from. Pick the level that matches how you want to live in it.' },
    { key: 'timeline', pill: 'Timeline', title: 'Timing and budget', intro: 'The last page. This helps us come back with something useful rather than something generic.' },
    { key: 'review', pill: 'Review', title: 'Check it over', intro: 'Everything you told us, in one place. Change anything you like before you send it.' }
  ];

  function sectionsFor(group) {
    return catalog.sections.filter(function (s) { return s.group === group; });
  }
  function groupMeta(key) {
    return catalog.groups.filter(function (g) { return g.key === key; })[0] || { title: key, intro: '' };
  }

  // ---- tiny DOM helpers --------------------------------------------------------
  function esc(s) {
    return String(s === null || s === undefined ? '' : s)
      .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;');
  }
  function $(id) { return document.getElementById(id); }
  function get(path) {
    var parts = path.split('.');
    return state.answers[parts[0]][parts[1]];
  }
  function set(path, value) {
    var parts = path.split('.');
    state.answers[parts[0]][parts[1]] = value;
    scheduleSave();
  }

  // ---- renderers --------------------------------------------------------------
  function choiceRow(path, options) {
    var cur = get(path);
    return '<div class="choice-row" data-group="' + esc(path) + '">' + options.map(function (o) {
      return '<button type="button" class="choice' + (cur === o.value ? ' active' : '') + '" data-choice data-path="' + esc(path) + '" data-value="' + esc(o.value) + '">' +
        esc(o.label) + (o.sub ? '<small>' + esc(o.sub) + '</small>' : '') + '</button>';
    }).join('') + '</div>';
  }
  function textField(path, label, opts) {
    opts = opts || {};
    var tag = opts.multiline ? 'textarea' : 'input';
    return '<div class="field"><label for="f-' + esc(path) + '">' + esc(label) + '</label>' +
      '<' + tag + ' class="text-input" id="f-' + esc(path) + '" data-path="' + esc(path) + '"' +
      (opts.multiline ? '' : ' type="' + (opts.type || 'text') + '"') +
      (opts.placeholder ? ' placeholder="' + esc(opts.placeholder) + '"' : '') +
      (opts.autocomplete ? ' autocomplete="' + esc(opts.autocomplete) + '"' : '') +
      (opts.multiline ? '>' + esc(get(path)) + '</textarea>' : ' value="' + esc(get(path)) + '">') +
      '</div>';
  }
  function stepper(path, label, min, max) {
    var v = get(path);
    return '<div class="field"><label for="f-' + esc(path) + '">' + esc(label) + '</label>' +
      '<div class="stepper"><button type="button" data-step-btn="-1" data-path="' + esc(path) + '" aria-label="Fewer">&minus;</button>' +
      '<input type="number" id="f-' + esc(path) + '" data-path="' + esc(path) + '" data-number min="' + min + '" max="' + max + '" value="' + (v === null || v === undefined ? '' : esc(v)) + '" placeholder="0">' +
      '<button type="button" data-step-btn="1" data-path="' + esc(path) + '" aria-label="More">+</button></div></div>';
  }
  function q(id, title, hint, body) {
    return '<div class="q" id="q-' + esc(id) + '"><h3>' + esc(title) + '</h3>' + (hint ? '<p class="hint">' + esc(hint) + '</p>' : '') + body +
      '<p class="error-msg" data-error-for="' + esc(id) + '"></p></div>';
  }
  function stepHead(label, title, intro) {
    return '<div class="step-head"><p class="step-label">' + esc(label) + '</p><h2>' + esc(title) + '</h2>' + (intro ? '<p class="intro">' + esc(intro) + '</p>' : '') + '</div>';
  }

  function tierBlock(section) {
    var cur = state.answers.sections[section.key] || '';
    var cards = TIERS.map(function (t) {
      var tier = section.tiers[t];
      var img = tier.image
        ? '<img class="tier-img" src="' + esc(tier.image) + '" alt="" loading="lazy" referrerpolicy="no-referrer">'
        : '<div class="tier-img placeholder" aria-hidden="true">' + esc(section.title) + '</div>';
      var inc = tier.includes && tier.includes.length
        ? '<details class="tier-inc"><summary>What this level typically includes</summary><ul>' + tier.includes.map(function (i) { return '<li>' + esc(i) + '</li>'; }).join('') + '</ul></details>'
        : '';
      return '<button type="button" class="tier' + (cur === t ? ' active' : '') + '" data-tier data-section="' + esc(section.key) + '" data-value="' + t + '" aria-pressed="' + (cur === t) + '">' +
        img + '<div class="tier-body"><div class="tier-level">' + TIER_LABEL[t] + '</div><div class="tier-head">' + esc(tier.headline) + '</div>' +
        '<div class="tier-desc">' + esc(tier.description) + '</div>' + inc + '</div></button>';
    }).join('');
    var alts = '<div class="alt-row">' +
      (section.optional ? '<button type="button" class="choice' + (cur === 'none' ? ' active' : '') + '" data-tier data-section="' + esc(section.key) + '" data-value="none">' + esc(section.none_label || 'Not needed') + '</button>' : '') +
      '<button type="button" class="choice' + (cur === 'undecided' ? ' active' : '') + '" data-tier data-section="' + esc(section.key) + '" data-value="undecided">Not sure yet, help me decide</button>' +
      '</div>';
    return '<div class="q" id="q-' + esc(section.key) + '" data-section-q="' + esc(section.key) + '"><h3>' + esc(section.title) + ': ' + esc(section.question) + '</h3>' +
      (section.help ? '<p class="hint">' + esc(section.help) + '</p>' : '') +
      '<div class="tier-grid">' + cards + '</div>' + alts +
      '<p class="error-msg" data-error-for="' + esc(section.key) + '">Pick a level, or tell us you are not sure yet.</p></div>';
  }

  function renderSite() {
    var a = state.answers;
    var countryOpts = '<option value="">Choose a country</option>' + COUNTRIES.map(function (c) {
      return '<option value="' + esc(c) + '"' + (a.site.country === c ? ' selected' : '') + '>' + esc(c) + '</option>';
    }).join('');
    var utilities = [['electric', 'Electricity'], ['water', 'Municipal water'], ['sewer', 'Sewer'], ['gas', 'Natural gas'], ['internet', 'Internet or fiber'], ['none', 'None of these reach the road yet']];
    return stepHead('Step 1 of ' + STEPS.length, STEPS[0].title, STEPS[0].intro) +
      q('contact', 'First, who are we building for?', 'So the estimate has a name on it. We already have your email from sign-in.',
        '<div class="field-grid">' + textField('contact.name', 'Your name', { autocomplete: 'name', placeholder: 'First and last name' }) +
        textField('contact.phone', 'Phone (optional)', { type: 'tel', autocomplete: 'tel', placeholder: 'So we can call if it is quicker' }) + '</div>') +
      q('country', 'Where is the site?', 'Country and state or region. If you have a street address or parcel number, add it.',
        '<div class="field-grid"><div class="field"><label for="f-site.country">Country</label><select class="text-input" id="f-site.country" data-path="site.country">' + countryOpts + '</select></div>' +
        textField('site.region', 'State, province or region', { placeholder: 'Michigan, Algarve, Ontario...' }) + '</div>' +
        textField('site.address', 'Address or parcel, if you have one', { multiline: true, placeholder: 'Street address, parcel ID, or the area you are looking in' })) +
      q('ownership', 'Do you own the land yet?', '', choiceRow('site.ownership', [
        { value: 'own', label: 'Yes, I own it' }, { value: 'contract', label: 'Under contract', sub: 'Closing soon' },
        { value: 'searching', label: 'Still searching' }, { value: 'help', label: 'I would like help finding land' }])) +
      q('access', 'How do you get to it?', 'Road access matters for the crane and the concrete trucks.', choiceRow('site.access', [
        { value: 'paved', label: 'Paved road' }, { value: 'gravel', label: 'Gravel or dirt road' }, { value: 'none', label: 'No road yet' }, { value: 'unsure', label: 'Not sure' }])) +
      q('utilities', 'What reaches the road?', 'Check everything that is already at the property line.',
        '<div class="check-list" data-multi="site.utilities">' + utilities.map(function (u) {
          var on = a.site.utilities.indexOf(u[0]) >= 0;
          return '<label class="check' + (on ? ' active' : '') + '"><input type="checkbox" data-multi-path="site.utilities" value="' + u[0] + '"' + (on ? ' checked' : '') + '> ' + esc(u[1]) + '</label>';
        }).join('') + '</div>' +
        textField('site.notes', 'Anything else about the site (optional)', { multiline: true, placeholder: 'Slope, views, trees, a well, a septic field, an HOA...' }));
  }

  function renderBuilding() {
    var a = state.answers;
    return stepHead('Step 2 of ' + STEPS.length, STEPS[1].title, STEPS[1].intro) +
      q('domes', 'How many domes?', 'Most homes are one or two. A compound can be more, all joined under one continuous shell.',
        stepper('building.domes', 'Number of domes', 1, 20) +
        textField('building.diameters', 'Approximate diameters, if you have them in mind', { placeholder: 'For example: one 12 m dome and one 8 m dome, or 40 ft and 26 ft' })) +
      q('floors', 'How many levels?', '', choiceRow('building.floors', [
        { value: '1', label: 'Single level' }, { value: 'loft', label: 'Single level plus a loft' }, { value: '2', label: 'Two full floors' }])) +
      q('foundation', 'What goes under it?', '', choiceRow('building.foundation', [
        { value: 'slab', label: 'Slab on grade' }, { value: 'basement', label: 'Full basement' }, { value: 'crawl', label: 'Crawl space' }, { value: 'unsure', label: 'Not sure yet' }])) +
      q('area', 'How big, all in?', 'Total finished floor area across every level. Type either unit and we fill in the other.',
        '<div class="area-row"><div class="field"><label for="f-area-m2">Square meters</label><div class="unit"><input class="text-input" type="number" inputmode="decimal" min="1" id="f-area-m2" data-area="m2" value="' + (a.building.area_m2 || '') + '" placeholder="150"><span>m2</span></div></div>' +
        '<div class="eq">=</div>' +
        '<div class="field"><label for="f-area-ft2">Square feet</label><div class="unit"><input class="text-input" type="number" inputmode="decimal" min="1" id="f-area-ft2" data-area="ft2" value="' + (a.building.area_ft2 || '') + '" placeholder="1600"><span>ft2</span></div></div></div>');
  }

  function renderProgram() {
    return stepHead('Step 3 of ' + STEPS.length, STEPS[2].title, STEPS[2].intro) +
      q('bedrooms', 'Bedrooms and bathrooms', 'Count a full bathroom as one with a tub or shower. A half bath is a toilet and sink.',
        '<div class="field-grid">' + stepper('program.bedrooms', 'Bedrooms', 0, 30) + stepper('program.bathrooms', 'Full bathrooms', 0, 30) + stepper('program.half_baths', 'Half bathrooms', 0, 30) + '</div>') +
      q('garage', 'Garage?', '', choiceRow('program.garage', [
        { value: 'none', label: 'No garage' }, { value: '1', label: 'One car' }, { value: '2', label: 'Two cars' }, { value: '3', label: 'Three or more' }])) +
      q('office', 'A dedicated office or study?', '', choiceRow('program.office', [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }])) +
      q('other', 'Other rooms', 'A pantry, a mudroom, a gym, a workshop, a guest suite, a greenhouse. Whatever the house needs to hold.',
        textField('program.other_rooms', 'List them here (optional)', { multiline: true, placeholder: 'Mudroom off the garage, a small home gym, covered outdoor kitchen...' }));
  }

  function renderGroup(stepIndex) {
    var step = STEPS[stepIndex];
    var g = groupMeta(step.group);
    var secs = sectionsFor(step.group);
    prefillDefaults(secs);
    return stepHead('Step ' + (stepIndex + 1) + ' of ' + STEPS.length, g.title, g.intro) +
      '<p class="hint" style="margin-top:14px;">Every level is a complete, well-built option. Good is honest and durable, Better is where most people land, Best is for the rooms you care most about. Open "what this level typically includes" on any card to see what sits behind it.</p>' +
      secs.map(tierBlock).join('');
  }

  // A single-level house has no stairs; a house with no garage has no garage
  // door. Prefilled once so the buyer is not asked something they already
  // answered, and only when the section is still blank.
  function prefillDefaults(secs) {
    var a = state.answers;
    secs.forEach(function (s) {
      if (a.sections[s.key]) return;
      if (s.key === 'stairs' && a.building.floors === '1') a.sections[s.key] = 'none';
      if (s.key === 'garage_doors' && a.program.garage === 'none') a.sections[s.key] = 'none';
    });
  }

  function renderSystems() {
    var comfort = ['heating', 'cooling', 'water_heater', 'fireplace'].map(function (k) { return catalog.sections.filter(function (s) { return s.key === k; })[0]; }).filter(Boolean);
    var energy = ['solar_pv', 'solar_thermal', 'battery_storage'].map(function (k) { return catalog.sections.filter(function (s) { return s.key === k; })[0]; }).filter(Boolean);
    prefillDefaults(comfort.concat(energy));
    return stepHead('Step 8 of ' + STEPS.length, STEPS[7].title, STEPS[7].intro) +
      comfort.map(tierBlock).join('') +
      q('electricity', 'How should the house make its electricity?', 'A utility hookup depends on how far the site is from the line, so we price that from your site rather than from a menu. Solar and batteries are on the next questions.',
        choiceRow('systems.electricity', [
          { value: 'grid', label: 'Grid only', sub: 'Connect to the utility, no solar' },
          { value: 'solar', label: 'Solar first, grid as backup', sub: 'Panels on the roof, still connected' },
          { value: 'hybrid', label: 'Grid plus solar and battery', sub: 'Connected, with storage for outages' },
          { value: 'offgrid', label: 'Fully off-grid', sub: 'No utility connection at all' }])) +
      energy.map(tierBlock).join('') +
      q('systems_notes', 'Anything else about systems?', '', textField('systems.notes', 'Optional', { multiline: true, placeholder: 'A well pump, an EV charger, a generator, radiant heat only in the bathrooms...' }));
  }

  function renderTimeline() {
    return stepHead('Step 9 of ' + STEPS.length, STEPS[8].title, STEPS[8].intro) +
      q('start', 'When would you like to break ground?', '', choiceRow('timeline.start', [
        { value: '3-6mo', label: '3 to 6 months' }, { value: '6-12mo', label: '6 to 12 months' }, { value: '12-24mo', label: '12 to 24 months' }, { value: 'exploring', label: 'Just exploring for now' }])) +
      q('budget', 'What budget range are you working with?', 'All-in for the build, in your own currency. A range is enough, and "would rather discuss it" is a fine answer.',
        choiceRow('timeline.budget', [
          { value: 'under-250k', label: 'Under 250 thousand' }, { value: '250-400k', label: '250 to 400 thousand' }, { value: '400-600k', label: '400 to 600 thousand' },
          { value: '600k-1m', label: '600 thousand to 1 million' }, { value: '1m-plus', label: 'Over 1 million' }, { value: 'discuss', label: 'Would rather discuss it' }]) +
        '<div class="field"><label>Currency</label>' + choiceRow('timeline.currency', [{ value: 'usd', label: 'US dollars' }, { value: 'eur', label: 'Euros' }, { value: 'other', label: 'Another currency' }]) + '</div>') +
      q('notes', 'Anything else we should know?', 'The things a form cannot ask. A view you want to frame, a room that matters more than the rest, a deadline, a worry.',
        textField('timeline.notes', 'Optional, but the most useful box on the page', { multiline: true, placeholder: 'Tell us in your own words.' }));
  }

  function renderReview() {
    var a = state.answers;
    var row = function (k, v) { return '<div class="review-row"><span class="k">' + esc(k) + '</span><span class="v' + (v ? '' : ' empty') + '">' + esc(v || 'Not answered') + '</span></div>'; };
    var lbl = function (map, v) { return v ? (map[v] || v) : ''; };
    var OWN = { own: 'Owns the land', contract: 'Under contract', searching: 'Still searching', help: 'Wants help finding land' };
    var ACC = { paved: 'Paved road', gravel: 'Gravel or dirt road', none: 'No road yet', unsure: 'Not sure' };
    var UTL = { electric: 'Electricity', water: 'Municipal water', sewer: 'Sewer', gas: 'Natural gas', internet: 'Internet', none: 'None yet' };
    var FLR = { '1': 'Single level', loft: 'Single level plus loft', '2': 'Two full floors' };
    var FND = { slab: 'Slab on grade', basement: 'Full basement', crawl: 'Crawl space', unsure: 'Not sure yet' };
    var GAR = { none: 'No garage', '1': 'One car', '2': 'Two cars', '3': 'Three or more' };
    var ELE = { grid: 'Grid only', solar: 'Solar first, grid as backup', hybrid: 'Grid plus solar and battery', offgrid: 'Fully off-grid' };
    var TML = { '3-6mo': '3 to 6 months', '6-12mo': '6 to 12 months', '12-24mo': '12 to 24 months', exploring: 'Just exploring' };
    var BUD = { 'under-250k': 'Under 250 thousand', '250-400k': '250 to 400 thousand', '400-600k': '400 to 600 thousand', '600k-1m': '600 thousand to 1 million', '1m-plus': 'Over 1 million', discuss: 'Would rather discuss it' };
    var CUR = { usd: 'US dollars', eur: 'Euros', other: 'Another currency' };
    var group = function (title, stepIndex, rows) {
      return '<div class="review-group"><h3>' + esc(title) + ' <a class="text-link" data-goto="' + stepIndex + '">Edit</a></h3><div class="review-table">' + rows + '</div></div>';
    };
    var tierText = function (s) {
      var v = a.sections[s.key];
      if (!v) return '';
      if (v === 'none') return s.none_label || 'Not needed';
      if (v === 'undecided') return 'Not sure yet';
      return TIER_LABEL[v] + ': ' + s.tiers[v].headline;
    };
    var groupRows = function (g) { return sectionsFor(g).map(function (s) { return row(s.title, tierText(s)); }).join(''); };
    var byKey = function (k) { return catalog.sections.filter(function (s) { return s.key === k; })[0]; };
    var html = stepHead('Step 10 of ' + STEPS.length, STEPS[9].title, STEPS[9].intro) +
      group('Site', 0,
        row('Name', a.contact.name) + row('Phone', a.contact.phone) + row('Country', a.site.country) + row('Region', a.site.region) + row('Address or parcel', a.site.address) +
        row('Land', lbl(OWN, a.site.ownership)) + row('Access', lbl(ACC, a.site.access)) + row('At the road', a.site.utilities.map(function (u) { return UTL[u] || u; }).join(', '))) +
      group('Building', 1,
        row('Domes', a.building.domes) + row('Diameters', a.building.diameters) + row('Levels', lbl(FLR, a.building.floors)) + row('Foundation', lbl(FND, a.building.foundation)) +
        row('Total size', a.building.area_m2 ? Number(a.building.area_m2).toLocaleString('en-US') + ' m2 (' + Number(a.building.area_ft2).toLocaleString('en-US') + ' ft2)' : '')) +
      group('Rooms', 2,
        row('Bedrooms', a.program.bedrooms === null ? '' : String(a.program.bedrooms)) + row('Full bathrooms', a.program.bathrooms === null ? '' : String(a.program.bathrooms)) +
        row('Half bathrooms', a.program.half_baths === null ? '' : String(a.program.half_baths)) + row('Garage', lbl(GAR, a.program.garage)) + row('Office', a.program.office === 'yes' ? 'Yes' : a.program.office === 'no' ? 'No' : '') + row('Other rooms', a.program.other_rooms)) +
      group('Kitchen and bathrooms', 3, groupRows('kitchen_bath')) +
      group('Interior', 4, groupRows('interior')) +
      group('Exterior', 5, groupRows('exterior')) +
      group('Water and outdoors', 6, groupRows('water_outdoors')) +
      group('Systems', 7,
        ['heating', 'cooling', 'water_heater', 'fireplace'].map(function (k) { return row(byKey(k).title, tierText(byKey(k))); }).join('') +
        row('Electricity', lbl(ELE, a.systems.electricity)) +
        ['solar_pv', 'solar_thermal', 'battery_storage'].map(function (k) { return row(byKey(k).title, tierText(byKey(k))); }).join('')) +
      group('Timeline', 8, row('Break ground', lbl(TML, a.timeline.start)) + row('Budget', a.timeline.budget ? BUD[a.timeline.budget] + (a.timeline.currency ? ' (' + CUR[a.timeline.currency] + ')' : '') : '') + row('Notes', a.timeline.notes)) +
      '<div class="consent-host"><div data-edh-consent="contact"></div></div>' +
      '<p class="error-msg" data-error-for="submit"></p>';
    return html;
  }

  function render() {
    var body = $('step-body');
    var i = state.step;
    var html;
    if (i === 0) html = renderSite();
    else if (i === 1) html = renderBuilding();
    else if (i === 2) html = renderProgram();
    else if (STEPS[i].group) html = renderGroup(i);
    else if (STEPS[i].key === 'systems') html = renderSystems();
    else if (STEPS[i].key === 'timeline') html = renderTimeline();
    else html = renderReview();
    body.innerHTML = html;
    if (i === STEPS.length - 1 && window.edhConsent && window.edhConsent.refresh) window.edhConsent.refresh();

    $('nav-back').style.visibility = i === 0 ? 'hidden' : 'visible';
    $('nav-next').textContent = i === STEPS.length - 1 ? 'Send it to us' : 'Continue';
    $('nav-save').style.display = i === STEPS.length - 1 ? 'none' : '';
    renderProgress();
    $('banner-error').classList.remove('show');
  }

  function renderProgress() {
    var pills = $('steps');
    pills.innerHTML = STEPS.map(function (s, idx) {
      var cls = idx === state.step ? 'current' : idx < state.step ? 'done' : '';
      return '<button type="button" class="step-pill ' + cls + '" data-goto="' + idx + '" role="tab" aria-selected="' + (idx === state.step) + '">' + (idx + 1) + '. ' + esc(s.pill) + '</button>';
    }).join('');
    var cur = pills.querySelector('.current');
    if (cur && cur.scrollIntoView) { try { cur.scrollIntoView({ block: 'nearest', inline: 'center' }); } catch (e) {} }
    $('bar-fill').style.width = Math.round((state.step / (STEPS.length - 1)) * 100) + '%';
  }

  // ---- validation --------------------------------------------------------------
  function validateStep(i) {
    var a = state.answers;
    var errors = [];
    var need = function (id, ok, msg) { if (!ok) errors.push({ id: id, msg: msg }); };
    if (i === 0) {
      need('contact', !!a.contact.name.trim(), 'Tell us your name so the estimate has one on it.');
      need('country', !!a.site.country, 'Pick the country the site is in.');
      need('ownership', !!a.site.ownership, 'Let us know where you are with the land.');
    } else if (i === 1) {
      need('domes', a.building.domes >= 1, 'At least one dome.');
      need('floors', !!a.building.floors, 'Pick the number of levels.');
      need('area', !!a.building.area_m2, 'Give us a rough total size in either unit.');
    } else if (i === 2) {
      need('bedrooms', a.program.bedrooms !== null && a.program.bathrooms !== null, 'Set the number of bedrooms and full bathrooms, even if it is zero.');
      need('garage', !!a.program.garage, 'Garage, or no garage?');
    } else if (STEPS[i].group) {
      sectionsFor(STEPS[i].group).forEach(function (s) { need(s.key, !!a.sections[s.key], 'Pick a level, or tell us you are not sure yet.'); });
    } else if (STEPS[i].key === 'systems') {
      ['heating', 'cooling', 'water_heater', 'fireplace', 'solar_pv', 'solar_thermal', 'battery_storage'].forEach(function (k) { need(k, !!a.sections[k], 'Pick a level, or tell us you are not sure yet.'); });
      need('electricity', !!a.systems.electricity, 'Pick how the house makes its electricity.');
    } else if (STEPS[i].key === 'timeline') {
      need('start', !!a.timeline.start, 'Pick a rough timeline.');
    }
    return errors;
  }

  function showErrors(errors) {
    document.querySelectorAll('.q.has-error').forEach(function (el) { el.classList.remove('has-error'); });
    document.querySelectorAll('.error-msg.show').forEach(function (el) { el.classList.remove('show'); });
    if (!errors.length) return;
    errors.forEach(function (e) {
      var el = document.querySelector('[data-error-for="' + e.id + '"]');
      if (el) { el.textContent = e.msg; el.classList.add('show'); }
      var qEl = $('q-' + e.id);
      if (qEl) qEl.classList.add('has-error');
    });
    var first = $('q-' + errors[0].id);
    if (first && first.scrollIntoView) first.scrollIntoView({ behavior: 'smooth', block: 'start' });
  }

  function allComplete() {
    for (var i = 0; i < STEPS.length - 1; i++) if (validateStep(i).length) return i;
    return -1;
  }

  // ---- save / resume ------------------------------------------------------------
  function token() {
    return state.session && state.session.access_token;
  }
  function api(method, body) {
    return SB.auth.getSession().then(function (res) {
      var session = res && res.data && res.data.session;
      if (!session) throw new Error('no session');
      state.session = session;
      return fetch('/api/intake', {
        method: method,
        headers: { 'Authorization': 'Bearer ' + session.access_token, 'Content-Type': 'application/json', Accept: 'application/json' },
        body: body ? JSON.stringify(body) : undefined
      }).then(function (r) { return r.json().catch(function () { return { ok: false }; }).then(function (j) { j._status = r.status; return j; }); });
    });
  }
  function setSaveState(text, isErr) {
    var el = $('save-state');
    el.textContent = text;
    el.classList.toggle('err', !!isErr);
  }
  function scheduleSave() {
    clearTimeout(state.saveTimer);
    setSaveState('Unsaved changes');
    state.saveTimer = setTimeout(function () { save(); }, 1500);
  }
  function save() {
    clearTimeout(state.saveTimer);
    if (!token()) return Promise.resolve(false);
    state.saving = true;
    setSaveState('Saving...');
    return api('POST', { action: 'save', step: state.step, answers: state.answers, locale: 'us' }).then(function (res) {
      state.saving = false;
      if (res && res.ok) {
        state.lastSaved = new Date();
        setSaveState('Saved ' + timeLabel(state.lastSaved));
        return true;
      }
      setSaveState((res && res.error) || "Couldn't save just now. Your answers are still on this page.", true);
      return false;
    }).catch(function () {
      state.saving = false;
      setSaveState("Couldn't save just now. Your answers are still on this page.", true);
      return false;
    });
  }
  function timeLabel(d) {
    return d.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' });
  }

  function loadDraft() {
    return api('GET').then(function (res) {
      if (res && res.ok && res.draft) {
        state.answers = mergeAnswers(res.draft.answers);
        state.step = Math.min(Math.max(Number(res.draft.step) || 0, 0), STEPS.length - 1);
        state.resumed = true;
        var note = $('resume-note');
        var when = res.draft.updated_at ? new Date(res.draft.updated_at) : null;
        note.textContent = 'Welcome back. We kept your answers' + (when ? ' from ' + when.toLocaleDateString('en-US', { month: 'long', day: 'numeric' }) + ' at ' + timeLabel(when) : '') + ', and you are back on the page you left.';
        note.style.display = '';
        if (when) { state.lastSaved = when; }
      } else {
        state.answers = emptyAnswers();
        state.step = 0;
        $('resume-note').style.display = 'none';
      }
    }).catch(function () {
      $('resume-note').style.display = 'none';
    });
  }

  // ---- navigation --------------------------------------------------------------
  function goTo(i, opts) {
    opts = opts || {};
    if (i < 0 || i >= STEPS.length) return;
    if (!opts.skipValidation && i > state.step) {
      // Moving forward: every step between here and there has to be complete.
      for (var s = state.step; s < i; s++) {
        var errs = validateStep(s);
        if (errs.length) {
          if (s !== state.step) { state.step = s; render(); }
          showErrors(errs);
          return;
        }
      }
    }
    state.step = i;
    // The welcome-back banner has done its job once the buyer moves on.
    $('resume-note').style.display = 'none';
    render();
    window.scrollTo({ top: $('intake-app').offsetTop - 70, behavior: 'smooth' });
    save();
  }

  function submit() {
    var incomplete = allComplete();
    if (incomplete >= 0) {
      state.step = incomplete;
      render();
      showErrors(validateStep(incomplete));
      return;
    }
    var btn = $('nav-next');
    btn.disabled = true;
    btn.textContent = 'Sending...';
    var consent = (window.edhConsent && window.edhConsent.read) ? window.edhConsent.read('contact') : null;
    api('POST', { action: 'submit', answers: state.answers, consent: consent, locale: 'us' }).then(function (res) {
      btn.disabled = false;
      btn.textContent = 'Send it to us';
      if (res && res.ok) {
        try { document.dispatchEvent(new CustomEvent('edh:lead-success', { detail: { formType: 'intake' } })); } catch (e) {}
        $('intake-app').style.display = 'none';
        $('intake-done').style.display = '';
        window.scrollTo({ top: $('intake-done').offsetTop - 90, behavior: 'smooth' });
        return;
      }
      var msg = (res && res.error) || 'We could not send your answers just now. Please try again in a moment.';
      var banner = $('banner-error');
      banner.textContent = msg;
      banner.classList.add('show');
      var errEl = document.querySelector('[data-error-for="submit"]');
      if (errEl) { errEl.textContent = msg; errEl.classList.add('show'); }
    }).catch(function () {
      btn.disabled = false;
      btn.textContent = 'Send it to us';
      var banner = $('banner-error');
      banner.textContent = 'We could not send your answers just now. Please try again in a moment.';
      banner.classList.add('show');
    });
  }

  // ---- events (delegated) ------------------------------------------------------
  function setAreaFrom(unit, raw) {
    var n = parseFloat(raw);
    var b = state.answers.building;
    if (!isFinite(n) || n <= 0) {
      b.area_m2 = null; b.area_ft2 = null;
      $(unit === 'm2' ? 'f-area-ft2' : 'f-area-m2').value = '';
      scheduleSave();
      return;
    }
    b.area_entered = unit;
    if (unit === 'm2') { b.area_m2 = Math.round(n); b.area_ft2 = Math.round(n * M2_TO_FT2); $('f-area-ft2').value = b.area_ft2; }
    else { b.area_ft2 = Math.round(n); b.area_m2 = Math.round(n / M2_TO_FT2); $('f-area-m2').value = b.area_m2; }
    scheduleSave();
  }

  function wire() {
    var body = $('step-body');

    body.addEventListener('click', function (ev) {
      var t = ev.target.closest ? ev.target.closest('[data-choice],[data-tier],[data-step-btn],[data-goto],summary') : null;
      if (!t) return;
      if (t.tagName === 'SUMMARY') { ev.stopPropagation(); return; } // let <details> toggle without selecting the card
      if (t.hasAttribute('data-choice')) {
        var path = t.getAttribute('data-path');
        set(path, t.getAttribute('data-value'));
        body.querySelectorAll('[data-choice][data-path="' + path + '"]').forEach(function (b) { b.classList.toggle('active', b === t); });
        clearError(t);
      } else if (t.hasAttribute('data-tier')) {
        var key = t.getAttribute('data-section');
        state.answers.sections[key] = t.getAttribute('data-value');
        scheduleSave();
        body.querySelectorAll('[data-tier][data-section="' + key + '"]').forEach(function (b) {
          var on = b === t;
          b.classList.toggle('active', on);
          if (b.classList.contains('tier')) b.setAttribute('aria-pressed', String(on));
        });
        clearError(t);
      } else if (t.hasAttribute('data-step-btn')) {
        var p = t.getAttribute('data-path');
        var input = body.querySelector('input[data-path="' + p + '"]');
        var cur = input.value === '' ? null : Number(input.value);
        var min = Number(input.min), max = Number(input.max);
        var next = (cur === null ? (min > 0 ? min : 0) : cur) + Number(t.getAttribute('data-step-btn'));
        if (cur === null && Number(t.getAttribute('data-step-btn')) < 0) next = min;
        next = Math.max(min, Math.min(max, next));
        input.value = next;
        set(p, next);
        clearError(t);
      } else if (t.hasAttribute('data-goto')) {
        ev.preventDefault();
        goTo(Number(t.getAttribute('data-goto')), { skipValidation: true });
      }
    });

    body.addEventListener('input', function (ev) {
      var el = ev.target;
      if (el.hasAttribute('data-area')) { setAreaFrom(el.getAttribute('data-area'), el.value); clearError(el); return; }
      if (el.hasAttribute('data-number')) {
        var v = el.value === '' ? null : Math.max(Number(el.min), Math.min(Number(el.max), Number(el.value)));
        set(el.getAttribute('data-path'), v);
        clearError(el);
        return;
      }
      if (el.hasAttribute('data-path')) { set(el.getAttribute('data-path'), el.value); clearError(el); }
    });
    body.addEventListener('change', function (ev) {
      var el = ev.target;
      if (el.hasAttribute('data-multi-path')) {
        var path = el.getAttribute('data-multi-path');
        var list = get(path).slice();
        var val = el.value;
        if (el.checked) {
          if (val === 'none') list = ['none'];
          else { list = list.filter(function (x) { return x !== 'none'; }); if (list.indexOf(val) < 0) list.push(val); }
        } else {
          list = list.filter(function (x) { return x !== val; });
        }
        set(path, list);
        body.querySelectorAll('input[data-multi-path="' + path + '"]').forEach(function (cb) {
          cb.checked = list.indexOf(cb.value) >= 0;
          cb.closest('.check').classList.toggle('active', cb.checked);
        });
        return;
      }
      if (el.tagName === 'SELECT' && el.hasAttribute('data-path')) { set(el.getAttribute('data-path'), el.value); clearError(el); }
    });

    $('steps').addEventListener('click', function (ev) {
      var t = ev.target.closest ? ev.target.closest('[data-goto]') : null;
      if (!t) return;
      goTo(Number(t.getAttribute('data-goto')));
    });
    $('nav-back').addEventListener('click', function () { goTo(state.step - 1, { skipValidation: true }); });
    $('nav-next').addEventListener('click', function () {
      if (state.step === STEPS.length - 1) { submit(); return; }
      var errs = validateStep(state.step);
      if (errs.length) { showErrors(errs); return; }
      goTo(state.step + 1);
    });
    $('nav-save').addEventListener('click', function () {
      save().then(function (ok) {
        if (ok) setSaveState('Saved. You can close this page and come back any time; sign in with the same email and we will bring you right here.');
      });
    });
    $('who-signout').addEventListener('click', function (ev) {
      ev.preventDefault();
      save().then(function () { SB.auth.signOut().catch(function () {}); });
    });
    window.addEventListener('beforeunload', function () {
      if (state.saveTimer) { clearTimeout(state.saveTimer); if (token()) { try { navigator.sendBeacon && save(); } catch (e) {} } }
    });
  }

  function clearError(el) {
    var qEl = el.closest ? el.closest('.q') : null;
    if (!qEl) return;
    qEl.classList.remove('has-error');
    var msg = qEl.querySelector('.error-msg');
    if (msg) msg.classList.remove('show');
  }

  // ---- views -------------------------------------------------------------------
  function showGate() {
    $('intake-gate').style.display = '';
    $('intake-app').style.display = 'none';
    $('intake-done').style.display = 'none';
  }
  function showApp() {
    $('intake-gate').style.display = 'none';
    $('intake-done').style.display = 'none';
    $('intake-app').style.display = '';
    $('who-email').textContent = (state.session && state.session.user && state.session.user.email) || '';
    render();
    if (state.lastSaved) setSaveState('Saved ' + timeLabel(state.lastSaved));
  }

  // ---- auth (same pattern as pricing.html) -------------------------------------
  var authOverlay = $('auth-overlay');
  var authMethodsView = $('auth-methods-view');
  var authOtpView = $('auth-otp-view');
  var authEmailForm = $('auth-email-form');
  var authEmailInput = $('auth-email');
  var authEmailError = $('auth-email-error');
  var authOtpDesc = $('auth-otp-desc');
  var authOtpError = $('auth-otp-error');
  var authProviderError = $('auth-provider-error');
  var otpDigits = Array.prototype.slice.call(document.querySelectorAll('.otp-digit'));
  var pendingEmail = '';

  function openAuthModal() {
    authOverlay.classList.add('open');
    authOverlay.setAttribute('aria-hidden', 'false');
    authMethodsView.style.display = '';
    authOtpView.style.display = 'none';
    authEmailError.classList.remove('show');
    authProviderError.classList.remove('show');
    setTimeout(function () { authEmailInput.focus(); }, 50);
  }
  function closeAuthModal() {
    authOverlay.classList.remove('open');
    authOverlay.setAttribute('aria-hidden', 'true');
  }
  function showOtpView(email) {
    pendingEmail = email;
    authOtpDesc.textContent = 'We sent a 6-digit code to ' + email;
    authMethodsView.style.display = 'none';
    authOtpView.style.display = '';
    otpDigits.forEach(function (inp) { inp.value = ''; });
    authOtpError.classList.remove('show');
    otpDigits[0].focus();
  }
  function setBusy(btn, busy) {
    btn.disabled = busy;
    if (busy) { btn.setAttribute('data-label', btn.textContent); btn.textContent = 'One moment...'; }
    else if (btn.getAttribute('data-label')) { btn.textContent = btn.getAttribute('data-label'); }
  }

  $('auth-close').addEventListener('click', closeAuthModal);
  authOverlay.addEventListener('click', function (ev) { if (ev.target === authOverlay) closeAuthModal(); });
  $('auth-back-btn').addEventListener('click', function () { authOtpView.style.display = 'none'; authMethodsView.style.display = ''; });
  $('gate-start').addEventListener('click', function () {
    if (state.session) { showApp(); return; }
    openAuthModal();
  });

  function startOAuth(provider, btn) {
    authProviderError.classList.remove('show');
    setBusy(btn, true);
    SB.auth.signInWithOAuth({ provider: provider, options: { redirectTo: location.origin + '/intake' } }).then(function (res) {
      if (res && res.error) { setBusy(btn, false); authProviderError.textContent = 'Could not start sign-in, try again.'; authProviderError.classList.add('show'); }
    }).catch(function () { setBusy(btn, false); authProviderError.textContent = 'Could not start sign-in, try again.'; authProviderError.classList.add('show'); });
  }
  $('auth-google-btn').addEventListener('click', function () { startOAuth('google', this); });
  $('auth-linkedin-btn').addEventListener('click', function () { startOAuth('linkedin_oidc', this); });
  if (ENV.local) {
    // No OAuth providers are configured on the local stack; hide them rather
    // than show two buttons that cannot work.
    $('provider-list').style.display = 'none';
    $('auth-divider').style.display = 'none';
  }

  authEmailForm.addEventListener('submit', function (ev) {
    ev.preventDefault();
    var email = authEmailInput.value.trim();
    var ok = /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
    authEmailInput.classList.toggle('invalid', !ok);
    if (!ok) { authEmailError.textContent = 'Enter a valid email address.'; authEmailError.classList.add('show'); return; }
    authEmailError.classList.remove('show');
    var btn = $('auth-email-submit');
    setBusy(btn, true);
    SB.auth.signInWithOtp({ email: email, options: { shouldCreateUser: true } }).then(function (res) {
      setBusy(btn, false);
      if (res && res.error) { authEmailInput.classList.add('invalid'); authEmailError.textContent = 'Could not send the code, try again.'; authEmailError.classList.add('show'); return; }
      showOtpView(email);
    }).catch(function () {
      setBusy(btn, false);
      authEmailInput.classList.add('invalid'); authEmailError.textContent = 'Could not send the code, try again.'; authEmailError.classList.add('show');
    });
  });

  otpDigits.forEach(function (inp, idx) {
    inp.addEventListener('input', function () {
      var v = inp.value.replace(/[^0-9]/g, '');
      if (v.length > 1) {
        // A pasted code: spread it across the boxes.
        v.split('').slice(0, otpDigits.length - idx).forEach(function (ch, j) { otpDigits[idx + j].value = ch; });
        otpDigits[Math.min(idx + v.length, otpDigits.length) - 1].focus();
        return;
      }
      inp.value = v;
      if (v && idx < otpDigits.length - 1) otpDigits[idx + 1].focus();
      authOtpError.classList.remove('show');
    });
    inp.addEventListener('keydown', function (ev) { if (ev.key === 'Backspace' && !inp.value && idx > 0) otpDigits[idx - 1].focus(); });
  });
  $('auth-verify-btn').addEventListener('click', function () {
    var filled = otpDigits.every(function (inp) { return /^[0-9]$/.test(inp.value); });
    if (!filled) { authOtpError.textContent = 'Enter all 6 digits.'; authOtpError.classList.add('show'); return; }
    var code = otpDigits.map(function (inp) { return inp.value; }).join('');
    var btn = $('auth-verify-btn');
    setBusy(btn, true);
    SB.auth.verifyOtp({ email: pendingEmail, token: code, type: 'email' }).then(function (res) {
      setBusy(btn, false);
      if (res && res.error) { authOtpError.textContent = "That code didn't match, try again."; authOtpError.classList.add('show'); return; }
      closeAuthModal();
    }).catch(function () { setBusy(btn, false); authOtpError.textContent = "That code didn't match, try again."; authOtpError.classList.add('show'); });
  });
  $('auth-resend-link').addEventListener('click', function (ev) {
    ev.preventDefault();
    SB.auth.signInWithOtp({ email: pendingEmail, options: { shouldCreateUser: true } }).then(function (res) {
      authOtpError.textContent = res && res.error ? 'Could not resend the code, try again.' : 'Code resent to ' + pendingEmail;
      authOtpError.classList.add('show');
    });
  });

  function cleanAuthHash() {
    if (window.location.hash && /access_token=|refresh_token=|error=/.test(window.location.hash)) {
      history.replaceState(null, '', window.location.pathname + window.location.search);
    }
  }

  function onSignedIn(session) {
    state.session = session;
    closeAuthModal();
    loadDraft().then(showApp);
  }
  function onSignedOut() {
    state.session = null;
    state.answers = emptyAnswers();
    state.step = 0;
    state.lastSaved = null;
    showGate();
  }

  // ---- boot --------------------------------------------------------------------
  var bootSession = null;
  function boot() {
    wire();
    SB.auth.onAuthStateChange(function (event, session) {
      cleanAuthHash();
      if (event === 'SIGNED_OUT') { onSignedOut(); return; }
      if (event === 'SIGNED_IN' && session && session.user) {
        if (state.session && state.session.user && state.session.user.id === session.user.id) { state.session = session; return; }
        onSignedIn(session);
      }
    });
    SB.auth.getSession().then(function (res) {
      var session = res && res.data && res.data.session;
      if (session && session.user) onSignedIn(session);
      else showGate();
    }).catch(showGate);
  }

  fetch('/js/intake-catalog.json', { headers: { Accept: 'application/json' } })
    .then(function (r) { return r.json(); })
    .then(function (data) { catalog = data; boot(); })
    .catch(function () {
      var gate = $('intake-gate');
      gate.querySelector('.gate-actions').innerHTML = '<span class="save-state err">We could not load the form just now. Please refresh, or email EcoDomeHomes@memorablegreen.com.</span>';
    });
})();
